### ISSUE TITLE
Overall branding and direction

### ISSUE THREAD

**Issue by marykatefain** [Uptwinkles/uptwinkles#1]
I think it would better to focus on the space, and the use of the space, rather than our political philosophy. The philosophy and how that guides our decisions should be clearly laid out on a page dedicated to doing so, as well as clear by our actions.

I think we could also lay out a lot more about our vision for the house. Sort of a "if you build it they will come" thing. We may not have the space totally up and running yet, but we should still say on there that we are working on a deck garden where we grow our own food, a basement that can serve as an activist tech hub, etc. 

I would include:
- pictures of the house, events at the house, meals we've cooked, etc.
- mission and goals
- location, current website does not even say "Philly". I think we should say in Point Breeze, Philadelphia.
- information for people who want to use the space (ex. for activism)
- how to apply for a room, and whether or not we currently have space available
- talk clearly about our connections with animal rights and free software movements
- information for people who need temporary housing for non-humans (rescue situations). what our boundaries are and what we can and can not help with

I think the styles should be:
- less aggressive/militant
- more "peace and harmony" (whites, blues, greens, pinks)
- cute, but professional (we want to be taken seriously, but seen as nice and fun people)
- clean, simple fonts

Color scheme example (?) :
http://paletton.com/#uid=22w0u0kllllfs-6fStKqOcW-6cs

**Comment by alexgleason** [comment]
Agree with this. I've already been taking some pics of food to use as examples for what dinner looks like.

**Comment by marykatefain** [comment]
We're so

![](http://1.bp.blogspot.com/-2VT-nAlEgtE/T9fFYZjLVJI/AAAAAAAABKQ/l9Hev2E-R2E/s1600/Nsync+-+I%27ll+Never+Stop+-+%28Import+CD+Single%29+-+2000+-+%28Front+Scan+LR.jpg)

**Comment by alexgleason** [comment]
I'm envisioning a logo where each letter of "Uptwinkles" is a magazine cutout.

**Comment by marykatefain** [comment]
What do you think of this draft of the front page of the website? The gray areas are placeholder images for house pics. 

[draft-webdesign.pdf](https://github.com/Uptwinkles/uptwinkles/files/981280/draft-webdesign.pdf)

**Comment by marykatefain** [comment]
PNG for easier viewing:

![draf-webdesign](https://cloud.githubusercontent.com/assets/17955536/25777290/273ea80c-32a7-11e7-809c-0010bb852b92.png)

**Comment by marykatefain** [comment]
debating whether or not to give this one of those scrolling top navigation bars

**Comment by marykatefain** [comment]
Also Im flexible on the color scheme based on what colors end up going well with the house photos. We should take some good quality ones when the weather is nice.

**Comment by alexgleason** [comment]
Nice! I like it. I'm glad you did a mobile-first design. I think the layout is great and I'm not bothered by the colors. After seeing it up close I think we can find better fonts, but overall I'm digging it. Want to start coding it?

**Comment by marykatefain** [comment]
Yay, thanks! And yes, that's what I was hoping to work on tomorrow. I think the layout will be super flexible. And yeah. I'm not married to the fonts. I kinda just picked a couple that looked okay to start with.

**Comment by alexgleason** [comment]
Actually the fonts are growing on me a little, it looks kind of techy.

**Comment by alexgleason** [comment]
Just maybe a bit too sharp. Like, middle ages or pirate/gothic looking.

**Comment by marykatefain** [comment]
Update: this is happening on branch `new-design`. Feel free to check out progress and send feedback.

Lots of copy and imgs still needed.
