### ISSUE TITLE
Content Needed

### ISSUE THREAD

**Issue by marykatefain** [Uptwinkles/uptwinkles#2]
I wouldn't mind some backup on content creation if anyone wants to contribute to that. Checkout branch `new-design` to see where I'm at. This is the copy that needs to be written:

1. ~~Living at Uptwinkles~~
 ~~_About communal living, what it's like to live here, member expectations, application process_~

2. ~~Our Mission and Vision~~
 ~~_Self explanatory_~~

3. ~~Our Philosophy~~
 ~~_Why we do what we do. About anarcho-communism, basics about animal rights and free software, etc. Links to resources_~~

4. ~~Animal Rights~~
 ~~_Animal rights beliefs, vegan house, AR activism we support (DxE, PARA), getting involved_~~

5. ~~Free Software~~
 ~~_About free software and why it is an issue. What we can do and how we can help you be more secure._~~

6. ~~Space for Activists~~
 ~~_What the space can be used for, how to reserve a space_~~

7. Our Projects
 _Libre boot/free your tech, animal rights, communal living framework. More details from home page_

**Comment by marykatefain** [comment]
Update: I have created a template with filler text on each page that needs content. Just remove the veggie ipsum and write your own. Thanks!

**Comment by alexgleason** [comment]
Looks like this is done. We can make a new issue about "our projects" content if you want.
