### ISSUE TITLE
Typos under vegan house

### ISSUE THREAD

**Issue by alexgleason** [Uptwinkles/uptwinkles#22]
carnivor, purchaising

**Comment by alexgleason** [comment]
Free software page:

governemnt, add period after "being used"

Also on animal page, "headquarter" to "headquarters"

**Comment by alexgleason** [comment]
Free software page: thier

**Comment by marykatefain** [comment]
Are you fixing these as you find them and about to submit a PR? Or just pointing them out?

**Comment by marykatefain** [comment]
Okay, I can do them. Just didn't want to bother if they were all about to get closed in a new push from you
