### ISSUE TITLE
Top banner should have a background color

### ISSUE THREAD

**Issue by alexgleason** [Uptwinkles/uptwinkles#28]
This is somewhat of a technicality but IMO important to consider. The top banner has a background *image* but not a background color. This means that on a very slow connection, as the top banner image is loading, the text will appear white on white. This makes it illegible. It should be dark purple instead.

This is also important because it fails automated WCAG tests. See:

![screenshot from 2017-05-19 10 53 05](https://cloud.githubusercontent.com/assets/3639540/26253524/b18d8be8-3c81-11e7-9f73-5bf0c5fa5942.png)

False positives are more work for us because we have to memorize the false positives and discern them from the real failures. This could theoretically also produce errors every time if we incorporated an automated testing system into our git repo.

**Comment by marykatefain** [comment]
Good point. This is an easy fix, too

**Comment by alexgleason** [comment]
This is the addon I'm using btw. It's a free software addon for FireFox/Abrowser/Icecat. https://addons.mozilla.org/en-us/firefox/addon/wcag-contrast-checker/
