### ISSUE TITLE
Use hypens in URLs, not underscores

### ISSUE THREAD

**Issue by alexgleason** [Uptwinkles/uptwinkles#4]
Neither are technically "wrong" but hypens are expected at this point. No reason to stray from the norm here.

**Comment by marykatefain** [comment]
Do you mean in reference to the page names, like "animal-rights" vs "animal_rights" ?

**Comment by alexgleason** [comment]
Yep

**Comment by marykatefain** [comment]
I just pushed a commit that should fix this. Does the "fixes" thing only close an issue if it gets merged?

**Comment by alexgleason** [comment]
Yep
